# Generated by Django 6.0.1 on 2026-03-22 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exercise_user_birth_date_user_current_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('leg', 'Leg'), ('bicpe', 'Bicpe'), ('tricpe', 'Tricpe'), ('shoulder', 'Shoulder'), ('abs', 'Abs')], max_length=64)),
                ('name_of_exercise', models.CharField(max_length=300)),
                ('exercise_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('order', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exerciselibrary')),
            ],
        ),
        migrations.CreateModel(
            name='SetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plannedexercise')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('bulk', 'Bulk'), ('cut', 'Cut')], max_length=32)),
                ('description', models.TextField()),
                ('days_wanna_play', models.IntegerField(choices=[(3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_split', models.CharField(choices=[('PPL', 'Push/Pull/Legs'), ('CBAL', 'Chest/Back/Arms/Legs'), ('FF', 'Full Body/Full Body'), ('CBLAS', 'Chest/Back/Legs/Arms/Shoulders'), ('CBLASC', 'Chest/Back/Legs/Arms/Shoulders/Cardio')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usergoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='plannedexercise',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workoutday'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workoutplan'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workoutday'),
        ),
        migrations.AddField(
            model_name='setprogress',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workoutsession'),
        ),
        migrations.DeleteModel(
            name='User_Goal',
        ),
    ]
