# Generated by Django 6.0.1 on 2026-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exerciselibrary_plannedexercise_setprogress_usergoal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselibrary',
            name='exercise_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
