# Generated by Django 6.0.1 on 2026-03-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_exerciselibrary_exercise_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselibrary',
            name='is_cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlannedCardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_minutes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_in_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exerciselibrary')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workoutday')),
            ],
        ),
        migrations.CreateModel(
            name='CardioProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_minutes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_in_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workoutsession')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plannedcardio')),
            ],
        ),
    ]
