# Generated by Django 6.0.1 on 2026-03-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_exerciselibrary_is_cardio_plannedcardio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselibrary',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('leg', 'Leg'), ('bicpe', 'Bicpe'), ('tricpe', 'Tricpe'), ('shoulder', 'Shoulder'), ('abs', 'Abs'), ('cardio', 'Cardio')], max_length=64),
        ),
    ]
