# Generated by Django 6.0.1 on 2026-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_exerciselibrary_muscle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselibrary',
            name='name_of_exercise',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
