# Generated by Django 6.0.1 on 2026-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_exerciselibrary_name_of_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselibrary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
