# Generated by Django 6.0.1 on 2026-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_exerciselibrary_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='days_wanna_play',
            field=models.IntegerField(choices=[(3, '3 days'), (4, '4 days'), (5, '5 days')]),
        ),
    ]
