# Generated by Django 6.0.1 on 2026-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_usergoal_days_wanna_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutday',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='plan_split',
            field=models.CharField(blank=True, choices=[('PPL', 'Push/Pull/Legs'), ('CBAL', 'Chest/Back/Arms/Legs'), ('FF', 'Full Body/Full Body'), ('CBLAS', 'Chest/Back/Legs/Arms/Shoulders'), ('CBLASC', 'Chest/Back/Legs/Arms/Shoulders/Cardio')], max_length=32, null=True),
        ),
    ]
