# Generated by Django 6.0.1 on 2026-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_workoutday_day_alter_workoutplan_plan_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
