# Generated by Django 6.0.1 on 2026-04-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_workoutsession_is_completed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plannedcardio',
            unique_together={('workout_day', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='plannedexercise',
            unique_together={('workout_day', 'exercise')},
        ),
    ]
